In [3]:
import numpy as np
import pandas as pd
from scipy import stats

In [4]:
#series
data = [70,90,65,80,85]
print("mean",np.mean(data))

mean 78.0

In [5]:
print("median",np.median(data))

median 80.0

In [14]:
print("Most frequent value",stats.mode(data))

Most frequent value ModeResult(mode=np.int64(65), count=np.int64(1))

In [8]:
print(max(data)-min(data))

25

In [11]:
print("Variance",np.var(data))

Variance 86.0

In [12]:
print("SD",np.std(data))

SD 9.273618495495704

In [17]:
df=pd.DataFrame(data)

In [18]:
df

    0
0  70
1  90
2  65
3  80
4  85

In [19]:
df.describe() #foe know about everythig of the data

               0
count   5.000000
mean   78.000000
std    10.368221
min    65.000000
25%    70.000000
50%    80.000000
75%    85.000000
max    90.000000

In [33]:
pop= [45,50,55,60,65,70,75,80,85,90,
        52,58,63,67,72,77,82,88,91,95,
        40,48,53,59,64,69,74,79,84,89,
        46,51,57,62,66,71,76,81,86,92,
        44,49,54,61,68,73,78,83,87,93]

In [34]:
df=pd.DataFrame(pop)

In [36]:
print(np.var(pop))

225.7604

In [37]:
import random
samp = random.sample(pop,15)
print(samp)

[64, 84, 69, 63, 88, 87, 60, 49, 65, 95, 46, 52, 71, 61, 85]

In [30]:
print(np.var(pop))

225.7604

In [38]:
sample = np.var(pop,ddof=1)
print(sample)

230.36775510204083